# synced from apix-actions/.github/workflows/close-jira.yaml
name: Auto Close Jira

on:
  pull_request:
    types: [closed]

permissions: {}

jobs:
  close-jira:
    if: contains(github.event.pull_request.labels.*.name, 'auto_close_jira')
    permissions:
      contents: read
      pull-requests: read
    uses: mongodb/apix-action/.github/workflows/_close-jira.yaml@f7d2400a387dea2661651b14bbaf8c8f46c8bf66 # main
    secrets: inherit